### ISSUE TITLE
How to install the cob_simulation

### ISSUE THREAD

**Issue by jinhooi** [ipa320/cob_simulation#164]
I start to work with care-o-bot4. But I cannot install simulation by "http://wiki.ros.org/Robots/Care-O-bot/indigo" (I have confirmed that it was installed in the last year, but not now.)
So I want to install by cob_simulator but I don't know how to install by cob_simulator in github.
Before I activate the hardware, I want to simulation hard.
I want you to help me simulate.
Thank you.

**Comment by fmessmer** [comment]
Please provide more infromation about what you are doing:
 - what OS (version) are you using
 - what ROS Distoro are you using
 - what package are installed from apt
 - what repos are in your workspace (from source)
 - what command (roslaunch) are you executing
 - what error message is printed

**Comment by jinhooi** [comment]
I use the ubuntu 16.04 and ros kinetic
so I have set up by 'sudo apt-get install ros-kinectic-care-o-bot'
(I used ros indigo but when I set by 'sudo apt-get install ros-indigo-care-o-bot' I cannot install it. So I changed to ros kinetic.)

But I have some error issues.
I can launch that
"export ROBOT=cob4-5
export ROBOT_ENV=ipa-apartment
roslaunch cob_bringup_sim robot.launch"

but I cannot use other apt.
For example, when I use 'roslaunch cob_bringup dashboard.launch' 
error message is
error loading <rosparam> tag: 
	file does not exist [/opt/ros/kinetic/share/cob_default_robot_config/robots/!!NO_ROBOT_SET!!/script_server/command_gui_buttons.yaml]
XML is <rosparam command="load" file="$(arg pkg_robot_config)/robots/$(arg robot)/script_server/command_gui_buttons.yaml" ns="control_buttons"/>
The traceback for the exception was written to the log file

and other
when I command 'roslaunch cob_gazebo robot.launch'
error message is
while processing /opt/ros/kinetic/share/cob_bringup/robots/!!NO_ROBOT_SET!!.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/opt/ros/kinetic/share/cob_bringup/robots/!!NO_ROBOT_SET!!.xml'
The traceback for the exception was written to the log file

In addition, running other things produces similar errors.
I want to simulate variance environment in gazebo and then excute hardware (I have cob4-5).
please some help.

thank you.

**Comment by floweisshardt** [comment]
you're missing the `robot` launch argument or `ROBOT` environment variable. So either `export ROBOT=cob4-5` and `export ROBOT_ENV=ipa-apartment` in each terminal or provide launch file arguments, e.g. `roslaunch cob_bringup dashboard.launch robot:=cob4-5 robot_env:=ipa-apartment`. (The variables are exaplined in http://wiki.ros.org/care-o-bot#Robots.2BAC8-Care-O-bot.Environment_variables)

**Comment by jinhooi** [comment]
Thank you so much. I can solve some problem.
so I want to activate arm by my trajectory or point to point, could you give me some tutorial or example code?
