### ISSUE TITLE
Shaking walls in ipa-apartment

### ISSUE THREAD

**Issue by stefandoerr** [ipa320/cob_simulation#82]
@ipa-fxm @ipa-nhg 
Me and some of my students experienced some strange behaviors when simulating with the gazebo world ipa-apartment. From time to time the walls start shaking in a earth quake manner,  the doors of the elevators start walking around and sometimes whole areas are teleported to a different place.
In 'earth quake mode' there is nothing you can do than restart the whole simulation.

**Comment by fmessmer** [comment]
are you using debian packages or latest sources?
let's have a look together on Monday

**Comment by stefandoerr** [comment]
debian packages

**Comment by fmessmer** [comment]
There were controllers missing for the elevator doors...
#83 fixes it!

**Comment by fmessmer** [comment]
#84 has been merged!
@ipa-srd @dabarsch please let us know in case you still experience something strange when simulating ipa-apartment...
