### ISSUE TITLE
Erroneus max range scans in ipa-apartment simulation on indigo

### ISSUE THREAD

**Issue by stefandoerr** [ipa320/cob_simulation#95]
I've experienced a strange behaviour with the gazebo simulation of the ipa-apartment environment.
After starting the simulation and spawning the robot both scanners deliver scans with all range values  in max range. When I insert new objects from the gazebo menu the scan points coming from the new objects look fine (See screenshot below with the book shelf manually inserted)
It needs several restarts of gazebo to have a 'normal' simulation behavior.
I'm using the current release of cob_simulation on indigo. @ipa-flg @dabarsch experienced the same behavior on their PCs.

![issue](https://cloud.githubusercontent.com/assets/3657552/10308837/e7dc8e30-6c38-11e5-9dda-16199146d520.png)

**Comment by fmessmer** [comment]
@ipa-srd @ipa-flg @dabarsch
As already discussed, please investigate a bit more yourself.
Some hints:
- how about other (ipa320) environments (i.e. ipa-kitchen, ipa-factory) -> might have something to do with the meshes used within the environments
- how about other (official) gazebo environments
- have a look at the [ros_laser_plugin](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/indigo-devel/gazebo_plugins/src/gazebo_ros_laser.cpp) which is used by our [simulated lasers](https://github.com/ipa320/cob_common/blob/indigo_dev/cob_description/urdf/sensors/sick_s300_laser.gazebo.xacro#L31)

**Comment by fmessmer** [comment]
#103 seems to be a proposed fix...

**Comment by fmessmer** [comment]
fixed once `gazebo-ros-2.4.10` is released (http://repositories.ros.org/status_page/ros_indigo_default.html?q=gazebo_ros) as explained in https://github.com/ipa320/cob_simulation/pull/103#issuecomment-197795405

**Comment by stefandoerr** [comment]
is fixed by https://github.com/ipa320/cob_simulation/pull/111
